/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.Student;
import model.Course;
import model.Lecturer;
import model.KRS;

/**
 *
 * @author LOQ
 */
public class InputNilai extends javax.swing.JFrame {
    ArrayList<Student> ListMahasiswa = new ArrayList<>();
    ArrayList<Course> ListMK = new ArrayList<>();
    ArrayList<Lecturer> ListLecturers = new ArrayList<>();
    final String[] semester = {"-- Pilih Semester --", "1", "2", "3"};
    final DefaultComboBoxModel comboModelSM = new DefaultComboBoxModel(semester);
    DefaultComboBoxModel<Student> comboModelMhs = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Course> comboModelCourse = new DefaultComboBoxModel<>();
    Student selectedStudent;
    Course selectedCourse;
    KRS krs;
    Lecturer selectedLecturer;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InputNilai.class.getName());

    /**
     * Creates new form InputNilai
     */
    public InputNilai() {
        initComponents();
        
        cmbName.setRenderer(new javax.swing.DefaultListCellRenderer() {
        @Override
        public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (value == null) setText("-- Pilih Nama Mahasiswa --");
            return this;
        }
        });
        cmbMataKuliah.setRenderer(new javax.swing.DefaultListCellRenderer() {
        @Override
        public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (value == null) setText("-- Pilih Matakuliah --");
            return this;
        }
        });
        
        ListMahasiswa.add(new Student("2515101021", "Rusdi", "001", "Ilmu Komputer", 20));
        ListMahasiswa.add(new Student("2515101093", "Ambatukam", "002", "Ilmu Komputer", 21));
        ListMahasiswa.add(new Student("2515101092", "Rehan", "003", "Ilmu Komputer", 22));
        ListMK.add(new Course("011", "Kalkulus", 3, 2));
        ListMK.add(new Course("022", "Matematika Diskrit", 3, 2));
        ListMK.add(new Course("033", "Sistem Digital", 2, 2));
        ListLecturers.add(new Lecturer("10101032", "Ayanokoji", "202303", "Kalkulus"));
        ListLecturers.add(new Lecturer("10101033", "Horikita", "202190", "Matematika Diskrit"));
        ListLecturers.add(new Lecturer("10101034", "Denia", "202538", "Sistem Digital"));
        
        comboModelMhs.addElement(null);
        for(Student mhs : ListMahasiswa){
            comboModelMhs.addElement(mhs);
        }
        comboModelCourse.addElement(null);
        for(Course crs: ListMK){
            comboModelCourse.addElement(crs);
  }
          DefaultTableModel model = (DefaultTableModel) jTableNilai.getModel();
          model.setRowCount(0);
    }
    
    private void setKRS(){
        int uas = Integer.parseInt(jTextFieldNilaiUAS.getText());
        int uts = Integer.parseInt(jTextFieldNilaiUTS.getText());
        int sikap = Integer.parseInt(jTextFieldNilaiSikap.getText());
        double rataRata = (uas + uts + sikap ) / 3.0;
        this.krs = new KRS(selectedCourse, rataRata);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmbMataKuliah = new javax.swing.JComboBox<>();
        jLabelKodeSKS = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNilaiUAS = new javax.swing.JTextField();
        jTextFieldNilaiSikap = new javax.swing.JTextField();
        jTextFieldNilaiUTS = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxSM = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        lblOutputGrade = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelJumlahSks = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbDosen = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbName = new javax.swing.JComboBox<>();
        jLabelNIM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableNilai = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas Matakuliah"));

        jLabel5.setText("Matakuliah");

        cmbMataKuliah.setModel(comboModelCourse);
        cmbMataKuliah.addActionListener(this::cmbMataKuliahActionPerformed);

        jLabelKodeSKS.setEditable(false);
        jLabelKodeSKS.setText("Kode dan SKS ");
        jLabelKodeSKS.addActionListener(this::jLabelKodeSKSActionPerformed);

        jLabel6.setText("Nilai");

        jTextFieldNilaiUAS.setText("0");

        jTextFieldNilaiSikap.setText("0");
        jTextFieldNilaiSikap.addActionListener(this::jTextFieldNilaiSikapActionPerformed);

        jTextFieldNilaiUTS.setText("0");
        jTextFieldNilaiUTS.addActionListener(this::jTextFieldNilaiUTSActionPerformed);

        jLabel7.setText("Semester");

        jComboBoxSM.setModel(comboModelSM);
        jComboBoxSM.addActionListener(this::jComboBoxSMActionPerformed);

        jLabel8.setText("Nilai Huruf");

        button.setText("Add");
        button.addActionListener(this::buttonActionPerformed);

        lblOutputGrade.setText("Nilai Huruf");

        jLabel9.setText("JumlahSKS:");

        jLabelJumlahSks.setText("0");

        jLabel10.setText("Nama Dosen");

        cmbDosen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Nama Dosen --", "Ayanokoji", "Horikita", "Denia" }));
        cmbDosen.addActionListener(this::cmbDosenActionPerformed);

        jLabel11.setText("Kode & SKS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jTextFieldNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNilaiSikap, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelKodeSKS, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(cmbDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelJumlahSks)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblOutputGrade)
                        .addGap(37, 37, 37)
                        .addComponent(button)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKodeSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNilaiSikap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabelJumlahSks))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cmbDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblOutputGrade))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button)
                        .addContainerGap())))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas Mahasiswa"));

        jLabel2.setText("Nama");

        cmbName.setModel(comboModelMhs);
        cmbName.addActionListener(this::cmbNameActionPerformed);

        jLabelNIM.setEditable(false);
        jLabelNIM.setText("NIM & PRODI");
        jLabelNIM.addActionListener(this::jLabelNIMActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabelNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Form Input Nilai");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 322, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTableNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "NAMA", "Matakuliah", "SKS", "Nilai", "Dosen"
            }
        ));
        jScrollPane3.setViewportView(jTableNilai);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMataKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMataKuliahActionPerformed
        // TODO add your handling code here:
        this.selectedCourse = (Course) cmbMataKuliah.getSelectedItem();
        if(selectedCourse != null){
            jLabelKodeSKS.setText(selectedCourse.getKode() + "| SKS" + Integer.toString(selectedCourse.getSKS()));
            String namaDosenPengampu = "-";
            String nidnDosenPengampu = "-";
            for(Lecturer dosen : ListLecturers){
                if(dosen.getKeahlian().equals(selectedCourse.getCourseName())){
                    namaDosenPengampu = dosen.getName();
                    nidnDosenPengampu = dosen.getNIDN();
                    break;             }
            }
           cmbDosen.setSelectedItem(namaDosenPengampu + " | NIDN: " + nidnDosenPengampu);

        }

    }//GEN-LAST:event_cmbMataKuliahActionPerformed

    private void jLabelKodeSKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelKodeSKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelKodeSKSActionPerformed

    private void jTextFieldNilaiSikapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNilaiSikapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNilaiSikapActionPerformed

    private void jTextFieldNilaiUTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNilaiUTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNilaiUTSActionPerformed

    private void jComboBoxSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSMActionPerformed
        // TODO add your handling code here:
        setKRS();
        lblOutputGrade.setText(this.krs.getGrade());
    }//GEN-LAST:event_jComboBoxSMActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        // TODO add your handling code here:
        if (selectedStudent == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Mohon isi data terlebih dahulu!\nPilih nama mahasiswa.",
                "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Validasi: matakuliah belum dipilih
        if (selectedCourse == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Mohon isi data terlebih dahulu!\nPilih matakuliah.",
                "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Validasi: semester belum dipilih (index 0 = item kosong pertama)
        if (jComboBoxSM.getSelectedIndex() < 0 || jComboBoxSM.getSelectedItem() == null || jComboBoxSM.getSelectedItem().toString().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Mohon isi data terlebih dahulu!\nPilih semester.",
                "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Validasi: KRS belum terbentuk
        if (cmbDosen.getSelectedIndex() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
            "Mohon isi data terlebih dahulu!\nPilih nama dosen.",
            "Peringatan",
            javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        selectedStudent.addKRS(krs);
        Object[] rowData = {
            selectedStudent.getNIM(),
            selectedStudent.getName(),
            selectedCourse.getNamaMk(),
            selectedCourse.getSks(),
            krs.getGrade(),
            selectedLecturer.getName()
        };
        DefaultTableModel model = (DefaultTableModel) jTableNilai.getModel();
        model.addRow(rowData);

// Simpan ke database
        try {
            double nilaiSikap = Double.parseDouble(jTextFieldNilaiSikap.getText().trim());
            double nilaiUts   = Double.parseDouble(jTextFieldNilaiUTS.getText().trim());
            double nilaiUas   = Double.parseDouble(jTextFieldNilaiUAS.getText().trim());
            int semester      = Integer.parseInt(jComboBoxSM.getSelectedItem().toString());

            int mahasiswaId  = getMahasiswaIdFromDB(selectedStudent.getNim());
            int dosenId      = getDosenIdFromDB(selectedLecturer.getNidn());
            int mataKuliahId = getMataKuliahIdFromDB(selectedCourse.getKode());

            model.KRS krsDB = new model.KRS(
                mahasiswaId, dosenId, mataKuliahId,
                nilaiSikap, nilaiUts, nilaiUas, semester
            );

            controller.KRSController krsController = new controller.KRSController();
            int result = krsController.create(krsDB);
            if (result > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data KRS berhasil disimpan!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data KRS!");
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nilai harus berupa angka!");
        }
    }//GEN-LAST:event_buttonActionPerformed

    private void cmbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNameActionPerformed
        // TODO add your handling code here:
        this.selectedStudent = (Student) cmbName.getSelectedItem();
        if(selectedStudent != null){
            jLabelNIM.setText(this.selectedStudent.getNIM() + " | Prodi: " + this.selectedStudent.getStudyProgress());

            int jumlahSks = this.selectedStudent.getJumlahSks();

            jLabelJumlahSks.setText(String.valueOf(jumlahSks));

        }

        // 2. Cetak ke dalam kotak teks (txtNimProdi)

    }//GEN-LAST:event_cmbNameActionPerformed

    private void cmbDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDosenActionPerformed
        // TODO add your handling code here:
        int index = cmbDosen.getSelectedIndex();
        if (index > 0) {
            selectedLecturer = ListLecturers.get(index - 1);
        } else {
            selectedLecturer = null;
        }
    }//GEN-LAST:event_cmbDosenActionPerformed

    private void jLabelNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelNIMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InputNilai().setVisible(true));
    }
    
    private int getMahasiswaIdFromDB(String nim) {
        try (java.sql.Connection conn = config.DBConnection.getConnection();
             java.sql.PreparedStatement stmt = conn.prepareStatement(
                 "SELECT id FROM mahasiswa WHERE nim = ?")) {
            stmt.setString(1, nim);
            java.sql.ResultSet rs = stmt.executeQuery();
            if (rs.next()) return rs.getInt("id");
        } catch (java.sql.SQLException e) {
            java.util.logging.Logger.getLogger(InputNilai.class.getName())
                .log(java.util.logging.Level.SEVERE, null, e);
        }
        return 0;
    }

    private int getDosenIdFromDB(String nidn) {
        try (java.sql.Connection conn = config.DBConnection.getConnection();
             java.sql.PreparedStatement stmt = conn.prepareStatement(
                 "SELECT id FROM dosen WHERE nidn = ?")) {
            stmt.setString(1, nidn);
            java.sql.ResultSet rs = stmt.executeQuery();
            if (rs.next()) return rs.getInt("id");
        } catch (java.sql.SQLException e) {
            java.util.logging.Logger.getLogger(InputNilai.class.getName())
                .log(java.util.logging.Level.SEVERE, null, e);
        }
        return 0;
    }

    private int getMataKuliahIdFromDB(String kode) {
        try (java.sql.Connection conn = config.DBConnection.getConnection();
             java.sql.PreparedStatement stmt = conn.prepareStatement(
                 "SELECT id FROM mata_kuliah WHERE kode = ?")) {
            stmt.setString(1, kode);
            java.sql.ResultSet rs = stmt.executeQuery();
            if (rs.next()) return rs.getInt("id");
        } catch (java.sql.SQLException e) {
            java.util.logging.Logger.getLogger(InputNilai.class.getName())
                .log(java.util.logging.Level.SEVERE, null, e);
        }
        return 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JComboBox<String> cmbDosen;
    private javax.swing.JComboBox<Course> cmbMataKuliah;
    private javax.swing.JComboBox<Student> cmbName;
    private javax.swing.JComboBox<String> jComboBoxSM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelJumlahSks;
    private javax.swing.JTextField jLabelKodeSKS;
    private javax.swing.JTextField jLabelNIM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableNilai;
    private javax.swing.JTextField jTextFieldNilaiSikap;
    private javax.swing.JTextField jTextFieldNilaiUAS;
    private javax.swing.JTextField jTextFieldNilaiUTS;
    private javax.swing.JLabel lblOutputGrade;
    // End of variables declaration//GEN-END:variables
}
